version: 0.2

phases:
  install:
    commands:
      - echo install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - docker build -t myodoo .
  post_build:
    commands:
      - echo Build completed on `date`
